first commit
Ralitnyi/training-repository pull request #1
Opened 2024-10-22 07:59 UTC by Ralitnyi

2024-10-22 19:27 UTC, krabatua requested changes

2024-10-22 19:27 UTC, krabatua commented on app.py
> +print("Hello world!")
Будь ласка зміни текст на "Hello Python"

2024-10-23 07:05 UTC, Ralitnyi commented on app.py
> +print("Hello world!")
Зробив зміни, перевірте будь ласка

2024-10-23 08:23 UTC, krabatua approved these changes

2024-10-23 08:32 UTC, merged